### ISSUE TITLE
Unable to configure integration ( `  No module named 'sampleclient' `)

### ISSUE THREAD

**Issue by johntdyer** [custom-components/healthchecksio#1]
## Version of the custom_component 1.0

Hass 0.97.2

## Configuration

n/a

## Describe the bug
when I go to the integration UI and select healthchecks.io from the list I get the following error in the logs:

```
2019-08-12 16:15:14 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading config flow for integration healthchecksio: No module named 'sampleclient'
```

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
uuuups.... where is that used 🤔

**Comment by ludeeus** [comment]
<https://github.com/custom-components/healthchecksio/releases/tag/0.1.1> Fixed
