### ISSUE TITLE
Why 5 minutes? Why not have it configured via the UI?

### ISSUE THREAD

**Issue by hindams** [custom-components/healthchecksio#104]
**Is your feature request related to a problem? Please describe.**
I'm trying to monitor the instance health and cross reference it with cpu % and temp, I need health checks to be less than 5 mins

**Describe the solution you'd like**
Why not configure it from the UI

**Describe alternatives you've considered**
Hardcoded it for now, but would prefer a cleaner option.

**Additional context**
N/A

**Comment by ludeeus** [comment]
<https://www.home-assistant.io/common-tasks/general/#why-use-an-automation-instead-of-changing-the-integrations-polling-configuration> That is the way to change it.
