### ISSUE TITLE
First ping works, subsequent ones never reach Healthcheck.io

### ISSUE THREAD

**Issue by quanturium** [custom-components/healthchecksio#13]
I've set up the plugin from HACS and the first ping works correctly. Any subsequence ping never reached their server. 

Here are the logs I've found from home-assistant.log

```
2021-01-13 16:53:55 ERROR (MainThread) [custom_components.healthchecksio] Could not update data - 
2021-01-13 16:53:55 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up healthchecksio platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/healthchecksio/binary_sensor.py", line 17, in async_setup_entry
    for check in hass.data[DOMAIN_DATA]["data"].get("checks", []):
KeyError: 'data'
```

EDIT: I was able to repro this on the previous and current version of this integration

**Comment by ishalem** [comment]
I have the same issue

**Comment by clockiee** [comment]
Hello I seem to be having the same problem as the two above, is there a work around or am I missing a setting? Any help would be appreciated so much

**Comment by quanturium** [comment]
If you're only using this extension to send a ping to healthcheck.io, an alternative and much simple solution is this:

> configuration.yaml
```
rest_command:
  healthcheckio:
    url: HEALTHCHECKIO_URL (e.g. https://hc-ping.com/xxxxxx)
    method: GET
```

> automation.yaml
```
- id: "1610586454189"
  alias: Healthcheckio ping
  description: ""
  trigger:
    - platform: time_pattern
      minutes: "/2"
  condition: []
  action:
    - service: rest_command.healthcheckio
      data: {}
  mode: single
```

This will send a ping every other minute to your healhcheckio endpoint.

**Comment by clockiee** [comment]
That's what I ended up doing and now it's working thank you
