### ISSUE TITLE
Add the ability to change the ping interval

### ISSUE THREAD

**Issue by eyalcha** [custom-components/healthchecksio#14]
Currently the throttle is 5 minutes. Add option to control the therotteling.

**Comment by poornachandratejasvi** [comment]
Hi, even I was trying to find option for changing the interval

**Comment by ludeeus** [comment]
I wonder if this can be dynamic based on the HC config for the monitor :thinking:

**Comment by LeoS3** [comment]
Any update on this, please?

**Comment by ludeeus** [comment]
Home Assistant now has this capability for all integrations.
https://www.home-assistant.io/blog/2021/06/02/release-20216/#disable-polling-updates-on-any-integration
