### ISSUE TITLE
Missing from "add integration"

### ISSUE THREAD

**Issue by mcfrojd** [custom-components/healthchecksio#17]
## Version of the custom_component

1.0.0
## Configuration

```yaml

Add your logs here.

```

## Describe the bug
When i moved to HomeAssistant Blue i cant find the "Healthchecks.io" integration in home assistant
I have installed from hacs and restarted many times.
I get no errors but i dont have "Healthchecks.io" to chose in integrations.
It still appears in my old instant on my intel nuc.

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
As with _any_ custom integration that uses UI.

Clear your browser cache.

**Comment by mcfrojd** [comment]
Ofc my misstake, thank you @ludeeus
