### ISSUE TITLE
Unclear how to configure from the UI

### ISSUE THREAD

**Issue by Xinil** [custom-components/healthchecksio#18]
After adding HealthchecksIO via the HACS integrations area, there is no ability to edit the settings from the UI, like the readme describes.

<img width="492" alt="Screen Shot 2021-02-28 at 8 18 04 AM" src="https://user-images.githubusercontent.com/1168011/109425596-d7a9fc00-799d-11eb-925c-6b23d02be912.png">

![Uploading Screen Shot 2021-02-28 at 8.17.57 AM.png…]()

Are you supposed to add a new entity/device? The instructions are very unclear.

**Comment by ludeeus** [comment]
Like **all** other integrations that are added with UI configuration, you do **not** do that in HACS, but in the Home Assistant Frontend. Configuration -> Integrations.
