### ISSUE TITLE
could add healtchcheck logo in home assistant tags

### ISSUE THREAD

**Issue by hudsonbrendon** [custom-components/healthchecksio#32]
could add healtchcheck logo in home assistant tags.

![healthchecks io](https://user-images.githubusercontent.com/5201888/185994070-eeb883ca-cbd8-4d3f-8b33-03e5e99e5dd2.jpg)

Currently the integration is without an icon:

![image](https://user-images.githubusercontent.com/5201888/185994220-f6adaf4e-dd1d-447c-a7f5-1605c0f29152.png)

**Comment by ludeeus** [comment]
Anyone can add that, its not controlled or managed from this repository.
