### ISSUE TITLE
Allow for configuration of schedule

### ISSUE THREAD

**Issue by n00b001** [custom-components/healthchecksio#35]
On the "healthchecks.io" webpage, I can configure:
Period 	5 minutes
(The expected time between pings)
Grace Time 	15 minutes
(When a check is late, how long to wait to send an alert) 

This custom component should also allow configuration of those items

**Comment by Mincka** [comment]
I found this in previously closed issues:

1) Disable the default polling
https://github.com/custom-components/healthchecksio/issues/14#issuecomment-1046306207
BUT, I checked and this option is not available for this integration

Alternative, update the code and restart your instance:
https://github.com/custom-components/healthchecksio/blob/main/custom_components/healthchecksio/__init__.py#L30

2) Poll when you want using your own automation
https://github.com/custom-components/healthchecksio/issues/31

**Comment by ludeeus** [comment]
It is for all integrations, it's a system option that HA adds, not something each integration adds.

**Comment by Mincka** [comment]
So, why is it not available for this integration?
![image](https://user-images.githubusercontent.com/6184289/215350588-e934b091-5f8f-41dd-8c3c-ec544f2e1845.png)
![image](https://user-images.githubusercontent.com/6184289/215350599-2a860f3a-c088-46ea-965f-0a1ea2af5fb3.png)
