### ISSUE TITLE
Integration fails completly if initial setup fails

### ISSUE THREAD

**Issue by Lafunamor** [custom-components/healthchecksio#38]
The integration does not recover when the initial setup fails.

Unfortunately, I was not able to generate more helpful information than this log output:
```
ERROR (MainThread) [custom_components.healthchecksio] Could not update data -
```
Which seems to come from here:
https://github.com/custom-components/healthchecksio/blob/main/custom_components/healthchecksio/__init__.py#L118

On my Raspberry Pi 3 with HASSOS it fails to initialize the Integration about every second time and I have not yet been able to identify the problem. It seems that a simple retry should help but I'm not sure how I could force it to do so. I've even added a job that updates the sensory every 2 minutes.

**Comment by mcclown** [comment]
I have the same issue. I just upgraded to Home Assistant 2023.3, and now this integration fails to load on startup every time.  I get the same error.

```2023-04-05 09:25:19.582 ERROR (MainThread) [custom_components.healthchecksio] Could not update data - Cannot connect to host healthchecks.io:443 ssl:default [Try again]```

One thing I have noticed is that on startup, it appears to successfully reach healthchecks.io once, as I get a notification saying my server is online from healthchecks.io but then it doesn't hit the healthcheck.io endpoint again, so the check notifies me of a failure after the configured time.

**Comment by Mincka** [comment]
The integration recently started to fail to update way more often.
It skips ping for unknown reason. I have a curl in a 60 minutes loop on HA pinging a fake ID that never fails during the same period.

```
2023-06-22 11:36:41.619 ERROR (MainThread) [custom_components.healthchecksio] Could not update data -
2023-06-22 11:41:41.630 ERROR (MainThread) [custom_components.healthchecksio] Could not update data -
2023-06-22 11:46:41.636 ERROR (MainThread) [custom_components.healthchecksio] Could not update data -
```

```
Thu Jun 22 11:40:30 CEST 2023   OK (not found)
Thu Jun 22 11:41:31 CEST 2023   OK (not found)
Thu Jun 22 11:42:31 CEST 2023   OK (not found)
Thu Jun 22 11:43:31 CEST 2023   OK (not found)
Thu Jun 22 11:44:31 CEST 2023   OK (not found)
Thu Jun 22 11:45:31 CEST 2023   OK (not found)
Thu Jun 22 11:46:32 CEST 2023   OK (not found)
Thu Jun 22 11:47:32 CEST 2023   OK (not found)
```
