### ISSUE TITLE
Binary sensors not added in Home Assistant 2023.3.3

### ISSUE THREAD

**Issue by d4g** [custom-components/healthchecksio#39]
I am running
- Home Assistant 2023.3.3 
- Supervisor 2023.03.1 
- Operating System 9.5 
- Frontend 20230309.0 - latest 

I added the custom component via HACS and then added it via the integration. I get one successful ping after I restart HA, but none afterwards. I also cannot find any binary sensors matching the description.

**Comment by adamlynes** [comment]
Which API key did you use? I tried just adding it to HA using the read key but that didn't create anything. Once I used the "full" key it created the sensors.

> I am running
> 
> * Home Assistant 2023.3.3
> * Supervisor 2023.03.1
> * Operating System 9.5
> * Frontend 20230309.0 - latest
> 
> I added the custom component via HACS and then added it via the integration. I get one successful ping after I restart HA, but none afterwards. I also cannot find any binary sensors matching the description.

**Comment by thibaultmol** [comment]
I'm also very confused why the readme specifically states you give it the full key... why? it's just reading them, no?
