### ISSUE TITLE
Point to selfhosted instance of Healthchecks.io

### ISSUE THREAD

**Issue by stenso** [custom-components/healthchecksio#4]
Healthchecks.io can be selfhosted. See the docker image [here](https://hub.docker.com/r/linuxserver/healthchecks). I would like to see the ability to point to my hosted url.

**Comment by eldudemeister** [comment]
I would also be interested in this functionality.

**Comment by ludeeus** [comment]
<https://github.com/healthchecks/healthchecks/>
Will look into it.

**Comment by markusressel** [comment]
I have done some work to implement this, however, I am facing some weird exceptions. I tend to think that this is a problem of my internal network setup and not one of the implementation, but to be sure it would be great if some of you guys (@stenso @eldudemeister) could try it out on your end (just copy the files over like mentioned in the README).

**Comment by eldudemeister** [comment]
Sorry not been able to look at this before now. Ive installed the repository in HACS and when I configured in the UI it doesn’t ask for the site root url only the api key and check ID?

**Comment by markusressel** [comment]
@eldudemeister When checking the "self-hosted" box it should show a second config flow where you can enter the site root.

**Comment by eldudemeister** [comment]
I don’t have that as an option? Do I need to download a different version? 
![E10761B9-D1AD-4ECD-8FE9-20A2F5800AA5](https://user-images.githubusercontent.com/46422051/96823714-fbc06400-1424-11eb-9178-28882b27a7ce.png)

**Comment by markusressel** [comment]
Well you need to update the component, via HACS or manually. Maybe the PR is not in the latest release yet and you need to install "master".

**Comment by eldudemeister** [comment]
Got it thanks, downloaded the master branch and installed manually.
