### ISSUE TITLE
Sensors report Disconnected state but it is Started in healthchecks

### ISSUE THREAD

**Issue by jsddsfoh** [custom-components/healthchecksio#48]
## Describe the bug
The sensors report "Disconnected" every time it is in "Started" state as described in healthchecks docs:
https://healthchecks.sandtner.cc/docs/measuring_script_run_time/

![grafik](https://github.com/custom-components/healthchecksio/assets/73244374/21a5ca8d-7c57-444f-9158-7526ae181922)

I think this is related to #37.

Edit:
It seems more complicated, than I thought.
![grafik](https://github.com/custom-components/healthchecksio/assets/73244374/28848fcf-b116-49c0-9c2d-366bd2a3d262)
Home Assistant shows only Disconnected, when running for more than 5 minutes.
Where should I look next to identify the problem?

**Comment by ludeeus** [comment]
Fixed in #63

**Comment by dcrusader** [comment]
This still seems to be occurring.
## healthchecks.io:
![image](https://github.com/user-attachments/assets/63233673-411b-4c73-8ce4-9c2c1bcf4ef1)
## Device history
![image](https://github.com/user-attachments/assets/b37c49dc-e194-4361-b00e-079224c22ab5)
## Integration version 22.2.0
![image](https://github.com/user-attachments/assets/be6d7d2f-d357-47b5-bb94-ad4c7dd66f1f)

My apologies if I should have opened a new issue.
