### ISSUE TITLE
Sensor becomes "Unavailable" after reboot

### ISSUE THREAD

**Issue by shoguevara** [custom-components/healthchecksio#49]
Home Assistant Version:
Core 2024.2.2
Supervisor 2024.02.0
Operating System 11.5 
Frontend 20240207.1

Integration Version: 22.2.0

The sensor has a disclaimer: "This entity is no longer being provided by the healthchecksio integration. If the entity is no longer in use, delete it in settings."

The integration was added to HACS, than configured from the integration screen.
After initial configuration, everything works fine, ping is successfully received each 5 minutes. 
But after the restart, the sensor permanently switches to unavailable state and don't come back, unless the integration is deleted, reinstalled and reconfigured.

What's very odd, is that I don't see anything in logs related to this integration

I'm also on a pretty fresh Home Assistant installation, in fact so fresh, that I never edited configurations.yaml directly. 

Here you can unmistakably determine when HA was rebooted and when the integration was reinstalled
<img width="781" alt="Screenshot 2024-02-23 at 14 44 10" src="https://github.com/custom-components/healthchecksio/assets/7438784/7e050f97-1ebb-456a-b66b-8b5fd5772019">

**Comment by johntdyer** [comment]
Running into this myself

**Comment by johntdyer** [comment]
@ludeeus  it appears you might be the code owner here ... I also tried the fixes in both open PR's in my local env and ended up w/ the same situation after a restart, so safe to say those PR's dont fix this issue

**Comment by Zeronozero** [comment]
Same problem here. Any fix ? Thanks for help

**Comment by ludeeus** [comment]
Fixed in #63
