### ISSUE TITLE
Use of `async_add_job` is Deprecated (removal in HA 2025.4)

### ISSUE THREAD

**Issue by mathmaniac43** [custom-components/healthchecksio#50]
## Version of the custom_component

22.2.0

## Configuration

```yaml

Detected that custom integration 'healthchecksio' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/healthchecksio/__init__.py, line 76: hass.async_add_job(, please create a bug report at https://github.com/custom-components/healthchecksio/issues

```

## Describe the bug

This integration uses a now-deprecated API call to Home Assistant. I believe guidance to update to a non-deprecated way is here: https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job

## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
Removed in https://github.com/custom-components/healthchecksio/pull/51
