### ISSUE TITLE
Ping tests failing intermittently 

### ISSUE THREAD

**Issue by neilbrookins** [custom-components/healthchecksio#52]
When I look at the health checks logs I can see gaps where the ping test was intermittently missing. During these times I know HA was up and working and my internet was also up and working because no other alerts occurred.  So, somehow the connection between HA and the cloud service is not consistently reliable.  But all other services are functioning. This problem just started to occur at  on 6/26/24 at 8:45:01 AM so that’s 2 days now.  Before then it was working reliably without issue.  I also tried to update HA to see if a restart and upgrade would make any difference.  Same today as yesterday.  No improvement.  

Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240610.1
Pi 4 64-bit.  

I think my next step to troubleshoot is to approach this from both ends.  Ping the heathchecks site from a different computer and site.  And ping a different provider of this type of service from HA.  This way I can see which of those two combinations also has the same issue.

**Comment by matferna** [comment]
I have the exactly same problem 😔

**Comment by neilbrookins** [comment]
For me, the problem went away after about noon on Friday.  So the duration of the failures was about 51 hours total; just over 2 days.  

I did setup a ping test from a second site going to hc cloud server.  That has not yet failed, but it wasn’t running until after 3pm Friday.  So they have both been up for about 30 hours now.
