### ISSUE TITLE
How to install latest code to HACS?

### ISSUE THREAD

**Issue by MisterWS** [custom-components/healthchecksio#73]
When installing from HACS, it uses the ZIP file associated with the latest GitHub release - v2022.02.0.

There have been a number of fixes and enhancements to the codebase over the past few months - are there plans to issue a new GitHub release including these changes that HACS can install by default?

**Comment by andarotajo** [comment]
Interested in this as well

**Comment by ludeeus** [comment]
use the update entity it provides and use `main` as the version.
