### ISSUE TITLE
HA reporting that healthchecksio calls async_add_job

### ISSUE THREAD

**Issue by derekoharrow** [custom-components/healthchecksio#84]
Home Assistant (2024.10.4) is reporting the following:

`2024-10-29 16:29:42.566 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'healthchecksio' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4; Please review https://developers.home-assistant.io/blog/2024/03/13/deprecate_add_run_job for replacement options at custom_components/healthchecksio/__init__.py, line 76: hass.async_add_job(, please create a bug report at [https://github.com/custom-components/healthchecksio/issues](https://github.com/custom-components/healthchecksio/issues%3C/span%3E)`

and:

`2024-10-29 16:29:42.570 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration, healthchecksio with title: 519307a7-1484-4f7b-a27e-b31ebeec56c0 and entry_id: 01JBC66Q01HEJ4SWGB7QWBZKW0, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.`

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/healthchecksio/pull/51
