### ISSUE TITLE
Please version plugin 

### ISSUE THREAD

**Issue by johntdyer** [custom-components/healthchecksio#90]
This plugin has version 0.0.0 in manifest file despite several changes over time, infact i think we're past 90 PR's for this repo.  Can we please start versioning it .  Thank you

**Comment by ludeeus** [comment]
Its injected during releases.

**Comment by johntdyer** [comment]
@ludeeus  hrm.... ok but if that is the case then shouldn't the version in the manifest.json file on my system have  something other then 0.0.0 ?
